name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.4, 2.5, 2.6, 2.7]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby_version: ${{ matrix.ruby_version }}
      - name: Install FFmpeg
        use: mstksg/get-package@v1
        with:
          apt-get: ffmpeg
      - name: Bundle Dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec rake
