name: Publish
on: [release]
jobs:
  build:
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby_version: ${{ matrix.ruby_version }}
      - name: Install FFmpeg
        use: mstksg/get-package@v1
        with:
          apt-get: ffmpeg
      - name: Bundle Dependencies
        run: bundle install
      - name: Build Gem
        run: bundle exec rake build
